### ISSUE TITLE
I wait

### ISSUE THREAD

**Issue by c2j** [YuWVandy/KG-LLM-MDQA#1]

**Comment by pribadihcr** [comment]
+1

**Comment by YuWVandy** [comment]
Thank you for your interest and patient. The paper is currently under the internal check in the company. Once that is finished, will upload it immediately.

**Comment by ifrit98** [comment]
This has quite a lot of potential. Looking forward to this being open-sourced.

**Comment by uneetkumarsingh** [comment]
@YuWVandy Eagerly waiting!

**Comment by YuWVandy** [comment]
We really thank you for all your interest in our work. We will release the datasets and the code collecting/processing these datasets and constructing their KGs soon (Before the middle of Dec). The proprietary Company dataset is under review internally and will be released once completed. There is indeed another recent paper coming-out talking about specifically about this dataset. Feel free to check that out as well https://arxiv.org/abs/2309.08872.
