### ISSUE TITLE
Could you please include the complete process with all the experimental data？such as train_docs.json

### ISSUE THREAD

**Issue by celiatw** [YuWVandy/KG-LLM-MDQA#2]
Could you please include the complete process with all the experimental data on Dropbox？such as train_docs.json

**Comment by YuWVandy** [comment]
> Could you please include the complete process with all the experimental data on Dropbox？such as train_docs.json

Hi Celiatw,

 Thank you for your interest in our work!
 train_docs.json is generated after running the following command

```
cd Data-Collect/{dataset}
python3 process.py
```

Please note that files required to run the above command are stored in the corresponding folder in Dropbox!

Feel free to let me know if you have any further issue.

**Comment by antahiap** [comment]
I can't find the `process.py` script.

**Comment by YuWVandy** [comment]
> I can't find the `process.py` script.

Hi,
 Please go to the dropbox and you can find the process.py in the corresponding folder.
 
 Thank you!

Best,
Yu Wang
