### ISSUE TITLE
Missing Data Files in Data-Collect Directory

### ISSUE THREAD

**Issue by hippoley** [YuWVandy/KG-LLM-MDQA#5]
Hi Dr. Wang,

I've been exploring your exciting KG-LLM-MDQA project and I'm super impressed by the innovative approach you're taking with graph data mining and deep learning – it's seriously cool stuff! 🌟

I'm currently trying to get a deeper understanding of the data collection process and was hoping to run some of the code myself. However, it looks like there might be some files missing under the `Data-Collect/{dataset}` directory that are referenced in the `README.md`. I just wanted to reach out and check if these files are available somewhere else, or if they'll be updated in the repo anytime soon?

Getting access to these files would be a huge help and allow me and other enthusiasts to fully engage with your project. Plus, if there's any other way to support or contribute to your work, count me in – I'd love to be a part of this journey!

Thanks a bunch for your help and for sharing your amazing work with the world!

Best,
hippoley

**Comment by YuWVandy** [comment]
> Hi Dr. Wang,
> 
> I've been exploring your exciting KG-LLM-MDQA project and I'm super impressed by the innovative approach you're taking with graph data mining and deep learning – it's seriously cool stuff! 🌟
> 
> I'm currently trying to get a deeper understanding of the data collection process and was hoping to run some of the code myself. However, it looks like there might be some files missing under the `Data-Collect/{dataset}` directory that are referenced in the `README.md`. I just wanted to reach out and check if these files are available somewhere else, or if they'll be updated in the repo anytime soon?
> 
> Getting access to these files would be a huge help and allow me and other enthusiasts to fully engage with your project. Plus, if there's any other way to support or contribute to your work, count me in – I'd love to be a part of this journey!
> 
> Thanks a bunch for your help and for sharing your amazing work with the world!
> 
> Best, hippoley

Hi Hippoley,
Thank you for your interest in our work. For the missing files you mentioned in Data-collect/2WikiMQA/, they are in the corresponding folder in the dropbox. I attached the link on that Github Repo. You can directly access them via that link. Just in case, the link is here as well: https://www.dropbox.com/scl/fo/y9ydmvv0bj846klkfdin0/h?rlkey=epyzclz2kbcf2g4iuz0tojlm9&dl=0

Let me know if you have any further issue.
 
Best,
Yu Wang

**Comment by hippoley** [comment]
really appreciate for sending over the Dropbox link for the Data-Collect/2WikiMQA/ directory. It's just what I needed for my work on the KG-LLM-MDQA project.
