### ISSUE TITLE
Can you share fine-tuned LLAMA model weights?

### ISSUE THREAD

**Issue by RongxuanLai** [YuWVandy/KG-LLM-MDQA#8]
I download the files from DropBox, and find datasets and some models, except the fine-tuned LLAMA(2) weight files. Can you share fine-tuned LLAMA model weights? Thanks.

**Comment by YuWVandy** [comment]
> I download the files from DropBox, and find datasets and some models, except the fine-tuned LLAMA(2) weight files. Can you share fine-tuned LLAMA model weights? Thanks.

Hi Rongxuan,
 Thank you for your interest in our work. We have put the checkpoints and also the fine-tuned Lora weights in the attached Dropbox link. 
  (1) For the original pretrained llama checkpoints, please use this link to access the checkpoints.zip file, https://www.dropbox.com/home/Project/LLM-KG-Doc
  (2) For the fine-tined Lora weight, please use this link to access the Lora weight file, https://www.dropbox.com/home/Project/LLM-KG-Doc/LLaMA/out/lora/reason
  
  Let me know if you have any further issue!
